### ISSUE TITLE
Tests fail in debug mode

### ISSUE THREAD

**Issue by L3thal14** [brave/pagegraph-crawl#34]
## Steps to Reproduce
1. Use `debug: true` in config.js and run the tests.
This is encountered due to the previous tests' graphs not being cleared in `debug` mode: https://github.com/brave/pagegraph-crawl/blob/a1d99d0dab489d79a3500cf90694c626d11426f1/test/test.js#L45-L49

Most of the testcases end up failing because of this:
https://github.com/brave/pagegraph-crawl/blob/a1d99d0dab489d79a3500cf90694c626d11426f1/test/test.js#L96-L106

**Suggestion:** Copy/Move the generated graphs to another folder instead of not clearing the `output` folder

**Comment by ShivanKaul** [comment]
Move them to `debug_output`, I've come across this too, thanks for raising the issue!
