### ISSUE TITLE
Input list of URLs from a file

### ISSUE THREAD

**Issue by L3thal14** [brave/pagegraph-crawl#56]
I believe this feature was in the pipeline, but currently, only the first URL from the list is crawled:
https://github.com/brave/pagegraph-crawl/blob/0758ba99697afd7d3e30f92688430fe5c4faa69d/src/run.ts#L29-L31

https://github.com/brave/pagegraph-crawl/blob/0758ba99697afd7d3e30f92688430fe5c4faa69d/src/brave/crawl.ts#L70

It would be helpful if the support for providing a list of URLs from a file (probably CSV or JSON) is added for synchronous crawls.

**Comment by pes10k** [comment]
Iike most things, I suggest handing this with bash scripting, and would prefer to leave this out of the tool itself. Is there any reason ‘`cat FILE_OF_URLS | while read URL; do npm run crawl - - -u $URL …; done;`’ wouldn’t work? (‘xargs’ or ‘parallel’ would make that even nicer)

**Comment by L3thal14** [comment]
> I’m just very eager to keep the tool as narrow as possible

I think, yeah this makes sense then. I was thinking more along the lines of turning this into a standalone framework for large-scale crawls like [tracker-radar-collector](https://github.com/duckduckgo/tracker-radar-collector) or [OpenWPM](https://github.com/openwpm/OpenWPM), which is why I opened #57 as well, especially, since most of the projects using `pagegraph-crawl` seem to be written in python (including [pagegraph-tranco-crawl](https://github.com/brave-experiments/pagegraph-tranco-crawl)) and running `pagegraph-crawl` via subprocess or other methods.
